-- Tabela Garcom
CREATE TABLE [dbo].[TBGARCOM]
(
    [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [NOME] NVARCHAR(100) NOT NULL,
    [CPF] NVARCHAR(20) NOT NULL
);

-- Tabela Mesa
CREATE TABLE [dbo].[TBMESA]
(
    [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [NUMERO] INT NOT NULL,
    [CAPACIDADE] INT NOT NULL,
    [ESTAOCUPADA] BIT NOT NULL
);

-- Tabela Produto
CREATE TABLE [dbo].[TBPRODUTO]
(
    [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [NOME] NVARCHAR(100) NOT NULL,
    [VALOR] DECIMAL(18, 2) NOT NULL
);

-- Tabela Conta
CREATE TABLE [dbo].[TBCONTA]
(
    [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [TITULAR] NVARCHAR(100) NOT NULL,
    [MESA_ID] UNIQUEIDENTIFIER NOT NULL,
    [GARCOM_ID] UNIQUEIDENTIFIER NOT NULL,
    [ABERTURA] DATETIME2 NOT NULL,
    [FECHAMENTO] DATETIME2 NULL,
    [ESTAABERTA] BIT NOT NULL,

    CONSTRAINT FK_Conta_Mesa FOREIGN KEY ([MESA_ID]) REFERENCES [dbo].[TBMESA]([ID]),
    CONSTRAINT FK_Conta_Garcom FOREIGN KEY ([GARCOM_ID]) REFERENCES [dbo].[TBGARCOM]([ID])
);

-- Tabela Pedido (Relaciona Produto e Conta)
CREATE TABLE [dbo].[TBPEDIDO]
(
    [ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [CONTA_ID] UNIQUEIDENTIFIER NOT NULL,
    [PRODUTO_ID] UNIQUEIDENTIFIER NOT NULL,
    [QUANTIDADESOLICITADA] INT NOT NULL,

    CONSTRAINT FK_Pedido_Conta FOREIGN KEY ([CONTA_ID]) REFERENCES [dbo].[TBCONTA]([ID]),
    CONSTRAINT FK_Pedido_Produto FOREIGN KEY ([PRODUTO_ID]) REFERENCES [dbo].[TBPRODUTO]([ID])
);
